---
- name: 2.1-2.7 setting appropriate flags in docker configuration
  lineinfile: >
    dest=/etc/selinux/config
    regexp=^OPTIONS= 
    line="'--selinux-enabled --disable-legacy-registry --icc=false --log-driver=journald --group=docker --log-level=info --iptables=true'"
  notify: Reload docker
  tags:
   - scored
   - section2.1
   - section2.2
   - section2.3
   - section2.4
   - section2.5
   - section2.6

- meta: flush_handlers
  tags:
   - scored
   - section2.1
   - section2.2
   - section2.3
   - section2.4
   - section2.5
   - section2.6

- name: 2.1 Restrict network traffic between containers (Scored)
  shell: pgrep -a docker | grep '[i]cc=false'
  register: res
  failed_when: res.rc == 1
  changed_when: res.rc == 1
  always_run: yes
  tags:
   - scored
   - section2.1

- name: 2.2 Set the logging level (Scored)
  shell: pgrep -a docker | grep '[l]og-level=info'
  register: res
  failed_when: res.rc == 1
  changed_when: res.rc == 1
  always_run: yes
  tags:
   - scored
   - section2.2

- name: 2.3 Allow Docker to make changes to iptables (Scored)
  shell: pgrep -a docker | grep '[i]ptables=true'
  register: res
  failed_when: res.rc == 1
  changed_when: res.rc == 1
  always_run: yes
  tags:
   - scored
   - section2.3

- name: 2.4 Do not use insecure registries (Scored)
  shell: pgrep -a docker | grep '[i]nsecure-registry'
  register: res
  failed_when: res.rc == 0
  changed_when: res.rc == 0
  always_run: yes
  tags:
   - scored
   - section2.4

- name: 2.5 Do not use the aufs storage driver (Scored)
  debug: msg=" docker info | grep -e '^Storage Driver:\s*aufs\s*$' shold return nothing"
  tags:
   - scored
   - section2.5

- name: 2.6 Configure TLS authentication for Docker daemon (Scored) (in our case check if the socket is not used)
  shell: pgrep -a docker | grep \\-H
  register: res
  failed_when: res.rc == 0
  changed_when: res.rc == 0
  always_run: yes
  tags:
   - scored
   - section2.6

- name: 2.7 Set default ulimit as appropriate (Not Scored)
  shell: ulimit -n 90000
  tags:
   - notscored
   - section2.7

